version: '3.8'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=Inventory
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
      start_period: 10s

  app:
    build: ./
    container_name: 'inventory-app'
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy