spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/Inventory
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation:true
    database: postgresql
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: examplepassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
  jwt:
    secret-key: "7f8G&9hK@3jL#2mN$1pQ^5zR*8tW!0xV"
    char-lower: "abcdefghijklmnopqrstuvwxyz"
    number: "0123456789"
    other-char: "!@#$%&*()_+-=[]?"
    password-length: 12

server:
  error:
    include-message: never
